# fly.toml app configuration file generated for vae-3 on 2023-11-20T09:58:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "gru"

[build]
  image = "ghcr.io/livebook-dev/livebook:0.11.3"

[env]
  ELIXIR_ERL_OPTIONS = "-proto_dist inet6_tcp"
  LIVEBOOK_DATA_PATH = "/data"
  LIVEBOOK_HOME = "/data"
  LIVEBOOK_IP = "::"
  LIVEBOOK_ROOT_PATH = "/data"
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
